---
- name: Install HTCondor Central Manager on Pulsar
  become: yes
  hosts: all
  roles:
    - name: usegalaxy_eu.htcondor
      vars:
        condor_role: central-manager
        condor_copy_template: false
  post_tasks:
    - name: Condor auto approve
      ansible.builtin.cron:
        name: condor_auto_approve
        minute: 0
        job: "/usr/bin/condor_token_request_auto_approve -netblock {{ condor_ip_range }} -lifetime 3660"
